version: "3.8"

services:
  database:
    image: library/postgres:12.4-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      PGDATA: "/var/lib/postgresql/data/pgdata"

volumes:
  dbdata: