spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  flyway:
    enabled: true